docker:
  host: "unix:///var/run/docker.sock"
  insecureRegistry: "7.182.100.117:5000"
database:
  url: "postgresql+asyncpg://admin:root@postgres-service:5432/test_db"
  POSTGRES_USER: "admin"
  POSTGRES_PASSWORD: "root"
  POSTGRES_DB: "test_db"
registry:
  url: "7.182.100.117:5000"
  auth_needed: false
proxy:
  http_proxy: "http://7.182.101.51:3128"
  https_proxy: "http://7.182.101.51:3128"
  HTTP_PROXY: "http://7.182.101.51:3128"
  HTTPS_PROXY: "http://7.182.101.51:3128"
  NO_PROXY: "localhost,127.0.0.1,10.0.0.0/8"
  no_proxy: "localhost,127.0.0.1,10.0.0.0/8"
k8s:
  namespace: "default"
api:
  image: "leetcode-executor"
  tag: "latest"
  imagePullPolicy: "IfNotPresent"