apiVersion: v1
kind: ConfigMap
metadata:
  name: leetcode-executor-config
data:
  DOCKER_HOST: {{ .Values.docker.host }}
  DATABASE_URL: {{ .Values.database.url }}
  REGISTRY_URL: {{ .Values.registry.url }}
  REGISTRY_AUTH_NEEDED: {{ .Values.registry.auth_needed | quote}}
  NAMESPACE: {{ .Values.k8s.namespace }}
