apiVersion: v1
kind: ConfigMap
metadata:
  name: dind-daemon-config
data:
  daemon.json: |-
    {
    "proxies": {
    "http-proxy": "{{ .Values.proxy.http_proxy }}",
    "https-proxy": "{{ .Values.proxy.https_proxy }}"
    },
      "insecure-registries": ["{{ .Values.docker.insecureRegistry }}"]
    }