apiVersion: v1
kind: Service
metadata:
  name: leetcode-executor-service
spec:
  selector:
    app: leetcode-executor
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: {{ .Values.api.nodeport }}
  type: NodePort
